spring:
    datasource:
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASS}
        driver-class-name: com.mysql.cj.jdbc.Driver
        tomcat:
            testOnBorrow: true
            validation-query: SELECT 1
        hikari:
            max-lifetime: 60000

    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: validate      
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USER}
        password: ${MAIL_PASS}

        properties:
            mail:
                debug: true
                encoding: UTF-8
                smtp:
                    auth: true
                    "[starttls.enable]": true #YAML_SHOULD_ESCAPE
                    "[starttls.required]": true
             
logging:
  level:
       org:
           hibernate:
               SQL: debug

server:
    port: ${PORT}
