// Generated by https://quicktype.io

package com.conversorback.api.model;

import java.util.Date;

import lombok.Data;
// CLASE DE MAPEO JSON DESDE https://api.bitso.com/v3/trades/?book=btc_ars
@Data
public class Book {
    private String book;
    private Date createdAt;
    private String amount;
    private String makerSide;
    private Double price;
    private long tid;

    public Book(){}


}
