// Generated by https://quicktype.io

package com.conversorback.api.model;

import java.util.Date;

import lombok.Data;

@Data
public class Book {
    private String book;
    private Date createdAt;
    private String amount;
    private String makerSide;
    private Double price;
    private long tid;

    public Book(){}


}
