spring:
    datasource:
        # url: jdbc:mysql://megasolution.com.ar/conversordb
        # username: mfuhr
        # password: 2744mfuhR
        # driver-class-name: com.mysql.cj.jdbc.Driver
        # url: jdbc:mysql://localhost/conversordb?serverTimezone=America/Argentina/Ushuaia
        # username: admin
        # password: 2744mfuhR
        # driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://us-cdbr-east-02.cleardb.com/heroku_cc48a5336dea05b?reconnect=true
        username: b4b639b34a044a
        password: 9839a811
        driver-class-name: com.mysql.cj.jdbc.Driver
        tomcat:
            testOnBorrow: true
            validation-query: SELECT 1
        hikari:
            max-lifetime: 300000

    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: validate      
    mail:
        host: smtp.gmail.com
        port: 587
        username: mfuhr91@gmail.com
        password: solsdpsxqdviwchw

        properties:
            mail:
                debug: true
                encoding: UTF-8
                smtp:
                    auth: true
                    "[starttls.enable]": true #YAML_SHOULD_ESCAPE
                    "[starttls.required]": true
             
logging:
  level:
       org:
           hibernate:
               SQL: debug

server:
    port: ${PORT:8080}
